apiVersion : apps/v1
kind: Deployment
metadata:
  name: cnv-middleware-api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnv-middleware-api 
  template:
    metadata:
      labels:
        app: cnv-middleware-api  
    spec:
      containers:
        - name: cnv-middleware-api  
          image: IMAGE:TAG
          imagePullPolicy: Always
          env:
            - name: root-redirect
              value: /admin/
            - name: cors
              value: http://localhost,http://localhost:1234,http://conversation-platform.productdock.com/,https://conversation-platform.productdock.com/,https://conversation-platform.productdock.com/admin/,https://conversation-platform.productdock.com/admin/dashboard/
            
            # Admin related
            # - name: ADMIN_USER
            #   value: admin
            # - name: ADMIN_PASSWORD
            #   value: admin
            
            # TRACK
            - name: TRACK_LIFETIME_MONTHS
              value: "1"

            # ARANGO_DB
            # - name: ARANGO_HOST
            #   value: http://arango:8529
            # - name: ARANGO_USER
            #   value: root
            # - name: ARANGO_PASSWORD
            #   value: secret
            # - name: ARANGO_DATABASE
            #   value: conversation

            # NODERED related configs
            - name: USE_BUNDLED_NODERED
              value: "true"
            - name: NODERED_WS_CONNECTION
              value: ws://localhost:8080
            - name: NODERED_HTTP_CONNECTION
              value: http://localhost:1880
            - name: NODERED_HOME_DIR
              value: /mount
            - name: NODERED_ENABLE_PROJECTS
              value: "true"
            - name: NODERED_FLOW_FILE
              value: flows.json
            
          envFrom:
            - secretRef:
                name: cnv-middleware-secret
          ports:
            - containerPort: 3000
            - containerPort: 1880
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/mount"
              name: nodered-managed-disk
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

      volumes:
        - name: nodered-managed-disk
          persistentVolumeClaim:
            claimName: nodered-managed-disk-pvc
