apiVersion : apps/v1
kind: Deployment
metadata:
  name: arango 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arango
  template:
    metadata:
      labels:
        app: arango 
    spec:
      containers:
        - name: arango 
          image: arangodb:3.7.12
          imagePullPolicy: IfNotPresent 
          env:
            - name: ARANGO_ROOT_PASSWORD
              value: "nimda2022##"
          ports:
            - containerPort: 8529
          volumeMounts:
            - mountPath: "/var/lib/arangodb3"
              name: arango-managed-disk
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "512m"
      volumes:
        - name: arango-managed-disk
          persistentVolumeClaim:
            claimName: arango-managed-disk-pvc