apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vv-middleware-api
  annotations:
    nginx.org/websocket-services: vv-middleware-api
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls: 
    - secretName: admin-vv-tls
      hosts:
        - conversation-vv.productdock.com
  rules:
    - host: conversation-vv.productdock.com
      http:
        paths:
          - path: /
            backend:
              serviceName: vv-middleware-api
              servicePort: 3000
          - path: /red/
            backend:
              serviceName: vv-middleware-api
              servicePort: 1880
                