apiVersion: v1
kind: Service
metadata:
    name: vv-middleware-api
spec:
    type: LoadBalancer
    ports:
      - port: 3000
        protocol: TCP
    selector:
      app: vv-middleware-api