
name: Build and Deploy to GKE

on:
  #release:
  #  types: [created]
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  DEPLOYMENT_NAME: cnv-middleware-api
  IMAGE: cnv-platform-middleware
  REGISTRY: europe-west3-docker.pkg.dev
  NAMESPACE: cnv-platform
  SSH_USER: ${{ secrets.DEVELOPMENT_SSH_USER }}
  SSH_KEY: ${{ secrets.DEVELOPMENT_SSH_KEY }}
  SSH_HOST: ${{ secrets.DEVELOPMENT_SSH_HOST }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        
    # Get npm credentials
    - name: GCP NPM auth
      run: |-
        npx google-artifactregistry-auth .npmrc

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud auth configure-docker \
          europe-west3-docker.pkg.dev

    # Setup Bastion SSH
    - name: Setup SSH
      run: |-
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/development.key
        chmod 600 ~/.ssh/development.key
        cat >>~/.ssh/config <<END
        Host development
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/development.key
          StrictHostKeyChecking no
        END
        

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$REGISTRY/$PROJECT_ID/$NAMESPACE-container/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          -f Dockerfile \
         .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$REGISTRY/$PROJECT_ID/$NAMESPACE-container/$IMAGE:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
        alias kustomize=$(pwd)/kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Build manifests
      run: |-
        cd manifests/development/
        kustomize edit set image IMAGE:TAG=$REGISTRY/$PROJECT_ID/$NAMESPACE-container/$IMAGE:$GITHUB_SHA
        kustomize build > cnv-middleware-development.yaml
    
    - name: Deploy GCP
      run: |-
        cd manifests/development/
        scp cnv-middleware-development.yaml development:/home/$SSH_USER
        ssh development "ls -lah"
        ssh development NAMESPACE=$NAMESPACE DEPLOYMENT_NAME=$DEPLOYMENT_NAME "echo $NAMESPACE $DEPLOYMENT_NAME"
        ssh development NAMESPACE=$NAMESPACE DEPLOYMENT_NAME=$DEPLOYMENT_NAME "kubectl -n $NAMESPACE apply -f cnv-middleware-development.yaml"
        ssh development NAMESPACE=$NAMESPACE DEPLOYMENT_NAME=$DEPLOYMENT_NAME "kubectl -n $NAMESPACE rollout status deployment/$DEPLOYMENT_NAME"
        

